[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'none'"
    childSrc = "'none'"
    connectSrc = "'none'"
    fontSrc = "'none'"
    imgSrc = "'self' data:"
    scriptSrc = "'self'"
    styleSrc = "'self'"
    prefetchSrc = "'self'"
