[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    connectSrc = "'self' https://www.google-analytics.com https://*.algolia.net"
    fontSrc = "'self'"
    imgSrc = "'self' data: https://www.google-analytics.com https://*.githubusercontent.com https://cdn.buymeacoffee.com https://gravatar.com https://img.shields.io https://badge.fury.io https://travis-ci.com https://codecov.io https://api.codeclimate.com https://travis-ci.com https://github.com https://flat.badgen.net https://i.imgur.com https://static.threenine.co.uk https://gridsome.org"
    scriptSrc = "'self' https://www.google-analytics.com https://ssl.google-analytics.com https://www.googletagmanager.com https://*.algolia.net"
    styleSrc = "'self'"
    frameSrc = "https://www.youtube.com"
