[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'self'"
    connectSrc = "https://www.google-analytics.com"
    fontSrc = "'none'"
    imgSrc = "'self' data: https://www.google-analytics.com"
    scriptSrc = "'self' https://www.google-analytics.com https://ssl.google-analytics.com https://www.googletagmanager.com"
    styleSrc = "'self'"
